import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const lora = localFont({
	src: [
		{
			path: './fonts/Lora-Bold.ttf',
			weight: '700',
			style: 'normal',
		},
		{
			path: './fonts/Lora-Medium.ttf',
			weight: '500',
			style: 'normal',
		},
		{
			path: './fonts/Lora-SemiBold.ttf',
			weight: '600',
			style: 'normal',
		},
		{
			path: './fonts/Lora-Medium.ttf',
			weight: '500',
			style: 'normal',
		},
		{
			path: './fonts/Lora-Regular.ttf',
			weight: '400',
			style: 'normal',
		},
	],
	variable: '--font-lora',
})


export const metadata: Metadata = {
	title: 'Molamike | Devs',
	description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
		<html lang="en">
			<body className={`${lora.variable}  antialiased`}>{children}</body>
		</html>
	)
}
